name: Publish Package

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, 'chore(release):')"
    steps:
      - run: sudo timedatectl set-timezone Europe/Berlin
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Configuring Git
        run: |
          git config user.name "daniyel"
          git config user.email "danijel.h@gmail.com"
      - name: Prepare dependencies
        run: npm install --ignore-scripts
      - name: Release
        run: npm run release-it -- --ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
